apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource
data:
  datasource.yaml: |
    apiVersion: 1

    deleteDatasources:
      - name: prometheus
        orgId: 1

    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-server-cluster-ip-az.openshift-metrics.svc:9090 # << Service hostname
        jsonData:
          tlsSkipVerify: true
        isDefault: true
        version: 1
        editable: false
